### ISSUE TITLE
add reserved characters encode tests

### ISSUE THREAD

**Issue by fengmk2** [node-modules/urlencode#11]
https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters

**Comment by fengmk2** [comment]
![image](https://cloud.githubusercontent.com/assets/156269/9829460/28e4ba2a-5937-11e5-8cdb-010c9e2bedff.png)

**Comment by fengmk2** [comment]
![image](https://cloud.githubusercontent.com/assets/156269/9829463/3820a594-5937-11e5-893a-5b4553117231.png)

**Comment by Kezzsim** [comment]
Was this ever resolved?
I'm having trouble when my string contains single quote it doesn't know to replace it and that causes issues when I wrap my query in single quotes

**Comment by gajraj-gan** [comment]
same
