### ISSUE TITLE
require is not defined when use in angular2

### ISSUE THREAD

**Issue by Sophia-nguyen** [node-modules/urlencode#14]
Hi, 
I am using in my app with angular2, I can not use `import` so I loaded by `<script>` tag.
But an error occurs `require is not defined`. How can I resolve it?

Thanks,

**Comment by Invis1ble** [comment]
@Sophia-nguyen I had the similar issue. If you're using `angular-cli` and you want to import `urldecode`, you can follow steps that described here: https://github.com/angular/angular-cli#3rd-party-library-installation

**Comment by fengmk2** [comment]
only work on nodejs
