### ISSUE TITLE
Unable to encode single quotes '

### ISSUE THREAD

**Issue by kumarmanishc** [node-modules/urlencode#25]
Hello Team
First of all Thank you for this package this helped a lot.

However I found one issue here it's not able to encode single quotes string.

```
import { encode } from "urlencode";
const response = encode("Stad aan 't Haringvliet");
```

**Output:** Stad%20aan%20't%20Haringvliet
**Expected Output:** This should encode that single quotes as well with possible output **Stad%20aan%20%27t%20Haringvliet**

**Comment by fengmk2** [comment]
We encode the input string using encodeURIComponent, which does not encode single quotes.

**Comment by kumarmanishc** [comment]
Got it
Fixed as follows..

```
import { encode } from "urlencode";
const response = encode("Stad aan 't Haringvliet");
if (response.includes("'")) {
            response = response.split("'").join("%27");
          }
```
