### ISSUE TITLE
use querystring.stringify on node >= 0.11.14

### ISSUE THREAD

**Issue by fengmk2** [node-modules/urlencode#6]

**Comment by alsotang** [comment]
io.js 1.0 已经可以自定义 `encodeURIComponent`  和 `decodeURIComponent` 了。但是没发现说可以支持嵌套。
感觉现在 qs 和 querystring 各做了一部分，要是 https://github.com/node-modules/urlencode/pull/5 这个 pr 可以合的话，urlencode 就做全了

**Comment by fengmk2** [comment]
这个是qs来做的吧

**Comment by alsotang** [comment]
但是 qs 对于 utf8 之外的编码不支持
> 在 2015年1月15日，08:46，fengmk2 <notifications@github.com> 写道：
> 
> 这个是qs来做的吧 
> 
> Sent from my iPhone 
>

**Comment by dead-horse** [comment]
https://github.com/pillarjs/qs-strict 到这个模块上面去搞吧

**Comment by alsotang** [comment]
qs-strict 和 qs 是两个极端嘛。
我还是喜欢 qs 多一点。

2015-05-08 16:08 GMT+08:00 Yiyu He <notifications@github.com>:

**Comment by alsotang** [comment]
我指的 qs 就是 npm 上的 qs，不是 querystring 原生库

在 2015年5月8日 下午7:33，alsotang <alsotang@gmail.com>写道：

**Comment by dead-horse** [comment]
qs-strict 他们还没开始写吧，不过到时候应该会包括 qs 的功能在里面的

**Comment by alsotang** [comment]
他们 strict 的目的不就是为了不能嵌套吗？

2015-05-09 0:47 GMT+08:00 Yiyu He <notifications@github.com>:

**Comment by dead-horse** [comment]
https://github.com/koajs/qs/issues/5

**Comment by dead-horse** [comment]
不过把一个 querystring 搞到这么复杂，支持各种嵌套也是蛋疼
